//
//  global.h
//  Ari9
//
//  Created by 홍준 김 on 12. 2. 20..
//  Copyright (c) 2012년 앱달. All rights reserved.
//

#ifndef Ari9_global_h
#define Ari9_global_h

#define LAYOUT_TITLE_BAR_HEIGHT 35
#define LAYOUT_BOTTOM_TAB_BAR_HEIGHT 49

#define LAYOUT_LEFTSIDE CGRectMake(0, 0, 320/5, 480-LAYOUT_BOTTOM_TAB_BAR_HEIGHT-LAYOUT_TITLE_BAR_HEIGHT) 
#define LAYOUT_CONTENTS_SIDE CGRectMake(320/5, 0, 320/5*4, 480-LAYOUT_BOTTOM_TAB_BAR_HEIGHT - LAYOUT_TITLE_BAR_HEIGHT) 
#define LAYOUT_CONTENTS_FULL CGRectMake(0, LAYOUT_TITLE_BAR_HEIGHT, 320, 480-LAYOUT_BOTTOM_TAB_BAR_HEIGHT-LAYOUT_TITLE_BAR_HEIGHT) 


#endif
